name = "Stochascape"
uuid = "fe4461bf-3609-400d-85d7-d42d16fd8269"
authors = ["John Skovbekk"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
